### ISSUE TITLE
1st release todo

### ISSUE THREAD

**Issue by umisora** [umisora/github-checklist-by-filetype#8]
### Refactoring
- [x] Classify and organize classes #11 
- [ ] Error handlingwhen Github API Call failed.

### Test
- [x] Use mock
- [x] Add more test cases

### Feature
- [x] Support PR-Sync Type
- [x] Support PR-ReOpen Type
- [x] Support empty-line for CHECKLIST file
- [x] Support comment out with "#" prefix for CHECKLIST file
### Change Name
- [ ] filetype -> file-extention
- [ ] Give a cool name
